---
pubkey_jakkspc: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH0x+XS9+4psMxWpASboko+cyZITLYFKIO1jO4ACPk2m jakks@jakkspc"
pubkey_thinkpad: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG/rHPK87smZNfNKVOpmWsYohE2jXKxTARdiQeMMk99Z jakks@thinkpad"

authorized_keys_jakks:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"

authorized_keys_ansible:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"

