---
ansible_user: ansible

base_package_list:
  - vim-enhanced
  - tmux
  - git
  - podman

authorized_keys_jakks:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"

authorized_keys_ansible:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"
