---
ansible_user: ansible

package_list:
  - vim-enhanced
  - tmux
  - git
  - podman
  - chrony

service_list:
  - chronyd

authorized_keys_jakks:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"

authorized_keys_ansible:
  - "{{ pubkey_jakkspc }}"
  - "{{ pubkey_thinkpad }}"
