---
- name: Ensure nginx is installed
  dnf:
    name: nginx
    state: present

- name: ensure https traffic is allowed
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: create extra directory to store TLS configs
  file:
    path: /etc/nginx/tls.conf.d
    state: directory
    mode: 0755

- name: copy main nginx config file
  copy:
    src: nginx_confs/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: copy nginx config file for SSL
  copy:
    src: nginx_confs/tls_pyrah.us.conf
    dest: /etc/nginx/tls.conf.d/tls_pyrah.us.conf
    owner: root
    mode: 0644
  notify: restart nginx
