---
- name: Ensure nginx is installed
  dnf:
    name: nginx
    state: present

- name: ensure https traffic is allowed
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: create extra directory to store SSL configs
  file:
    path: /etc/nginx/ssl.conf.d
    state: directory
    mode: 0755

- name: copy main nginx config file
  copy:
    src: nginx-confs/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: copy nginx config file for SSL
  copy:
    src: nginx-confs/ssl-pyrah.us.conf
    dest: /etc/nginx/ssl.conf.d/ssl-pyrah.us.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: Ensure nginx service is enabled
  service:
    name: nginx
    state: started
    enabled: true
