---
all:
  hosts:
    armserver1:
      ansible_host: armserver1.ts.pyrah.us

    clusternode1:
      ansible_host: clusternode1.ts.pyrah.us

    mars:
      ansible_host: 100.69.198.104
      ansible_connection: local

rhel_servers:
  hosts:
    armserver1:

desktops:
  hosts:
    mars:

ungrouped:
  hosts:
    _failwhenfound: # dummy host that triggers failure when not specifying --limit, if playbook is set up to do so
      ansible_connection: local
