---
rhel_servers:
  hosts:
    armserver1:
      ansible_host: 100.67.244.2
      ansible_user: ansible

    microserver:
      ansible_host: 100.100.89.88
      ansible_user: ansible

desktops:
  hosts:
    jakkspc:
      ansible_host: 100.82.15.6
      ansible_connection: local

ungrouped:
  hosts:
    _failwhenfound: # dummy host that triggers failure when not specifying --limit, if playbook is set up to do so
      ansible_connection: local
