---
rhel_servers:
  hosts:

    armserver1:
      ansible_host: 100.87.193.234
      ansible_user: ansible
      
    microserver:
      ansible_host: 100.87.201.80
      ansible_user: ansible

desktops:
  hosts:

    jakkspc:
      ansible_host: localhost
      ansible_connection: local
