---
- name: Update all packages
  hosts: all
  become: true
  tasks:

    - name: Upgrade all packages - apt
      apt:
        upgrade: yes
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages - dnf
      dnf:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8