---
# Playbook for applying declarative configurations


- hosts: 
  - rhel_servers
  - deb_servers
  become: true
  vars_files:
    - vault.yml
  roles:
    - common
    - artis3n.tailscale

- hosts: armserver1
  become: true
  roles:
    - blogserver
