---
# Playbook for applying declarative configurations
- hosts: rhel_servers
  become: true
  roles:
    - common
    - artis3n.tailscale

- hosts: armserver1
  become: true
  roles:
    - blogserver
