---
- name: Install EPEL
  dnf:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install base packages (dnf)
  dnf:
    name: "{{ base_package_list | default('') }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

