---
- name: copy blog config file
  copy:
    src: nginx_confs/blog.conf
    dest: /etc/nginx/conf.d/blog.conf
    owner: root
    mode: 0644
  notify: restart nginx

- name: pull down static site from Github
  ansible.builtin.git:
    repo: https://github.com/NuclearPine/blog-static
    dest: /var/www/pyrah.us
  tags: ["update-blog", "never"]
  become: true
